POST http://localhost:8087/create
Content-Type: application/json

{
  "userEmail": "kendoe@a.com",
  "amount": 1050,
  "orderItems": [
    {
      "productId": "9ba00294-03b2-11ee-be56-0242ac120002",
      "quantity": 1,
      "price": 500
    },
    {
      "productId": "a0ef40de-03b2-11ee-be56-0242ac120002",
      "quantity": 2,
      "price": 250
    }
  ]
}