POST http://localhost:8087/create
Content-Type: application/json

{
  "userEmail": "kendoe@a.com",
  "amount": 49515,
  "orderItems": [
    {
      "productId": "5cb153fe-086b-11ee-be56-0242ac120002",
      "quantity": 1,
      "price": 15
    },
    {
      "productId": "5cb154f8-086b-11ee-be56-0242ac120002",
      "quantity": 11,
      "price": 4500
    }
  ]
}