server:
  port: 8083

spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  integration:
    channel:
      auto-create: true
  datasource:
    url: jdbc:postgresql://localhost:5436/postgres?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: postgres